### ISSUE TITLE
Document model

### ISSUE THREAD

**Issue by joerick** [tingbot/tide-electron#11]
Currently the app has only one window. The app should be able to have multiple tingapps open at once. All state should be specific to the document, not the app.

**Comment by Rob4001** [comment]
So you would prefer multiple windows with each having a single app to one window with multiple apps?

**Comment by joerick** [comment]
That's what I was thinking. Is that common on Linux/Windows?

**Comment by Rob4001** [comment]
I would not say it is Common or Uncommon on Windows and Linux but most IDEs I have used adopt single window multiple project. On Linux and Windows apps that use multiple windows get grouped together on a taskbar making it difficult to switch between due to certain ambiguities in the window switching implementations (only showing abbreviated titles or small screenshots of the window in question). 

It all ends up to personal taste/design. I can implement this either way :)

**Comment by joerick** [comment]
I've just checked out master. Great work with the refactor! I see you've got the explicit TingApp model in there, which is a step in the right direction.

I'm currently kicking around the idea of using Tide-Electron as the Mac IDE as well (abandoning the Objective-C codebase), and for Mac the paradigm would have to be 1 window per TingApp. This is one of the challenges of cross-platform frameworks! While the code is cross-platform, often the UI is not!

But for now this port is for Linux/Windows, so lets go with whatever makes sense on those platforms and I'll think about Mac later.

Does anyone else have a feeling about this, or perhaps some screenshots of other editors and how they accomplish the same thing?

**Comment by joerick** [comment]
Hey, been thinking more about this. I'm leaning more toward separate windows just so it's clear what all the controls do - e.g. when pressing the Run button which app runs, if the user does File>Save which app is saved, etc. Currently with the apps in the sidebar and buttons at the top it's not visually clear that Run/Upload will affect just that app. Maybe that's a consequence of the design with the buttons at the top, but it'd like to keep it consistent with the Mac app and also other references like Arduino/Processing.

**Comment by Rob4001** [comment]
Ok, No problem. I have been snowed under with work but I should have some free time upcoming soon
