### ISSUE TITLE
Build System

### ISSUE THREAD

**Issue by Rob4001** [tingbot/tide-electron#2]
It would be nice to have a build system for this project to easily push out releases for all the OSs

I was thinking TravisCI would be a good system to use as they support OSX compilation and also can directly deploy to the Github Releases system

I have been testing this on my now defunct TidePower repo and it seems to be working quite well

**Comment by joerick** [comment]
Sounds great! Travis looks like a good choice.

**Comment by Rob4001** [comment]
So my tests with TravisCI on the TidePower repo seem to be successful, it builds for all three Operating Systems and pushes installers to Github's Release system. I have tested the Windows and Linux generated files but as I have no access to an OSX machine I cannot test the dmg that is generated.

If you feel this is the way we wish to go I can modify that .travis.yml file to build Tide Electron
