### ISSUE TITLE
Side bar insert buttons

### ISSUE THREAD

**Issue by benpawle** [tingbot/tide-electron#26]
![new file folder import-v1](https://cloud.githubusercontent.com/assets/6080845/16883610/c5d8241c-4abc-11e6-99b0-daff6a8fc596.png)
Default and Rollover states of icons for:
1 ‘New file’ - creates new file
http://fontawesome.io/icon/file-code-o/

2 ‘New folder’ - creates new folder
http://fontawesome.io/icon/folder-o/

3 ‘Import’ - opens file browser to import an asset
<img width="30" alt="import- 2x" src="https://cloud.githubusercontent.com/assets/6080845/16883957/b5d1f88e-4abe-11e6-9506-54b286ac78fc.png">

**Comment by joerick** [comment]
Fixed in 537fe8d5e05f7c69b20e31256978497367eecc86
