### ISSUE TITLE
Automated Updates

### ISSUE THREAD

**Issue by Rob4001** [tingbot/tide-electron#39]
Electron has an automatic update system called squirrel,

If we can setup http://nuts.gitbook.com/ on the tingbot site we can provide this functionallity

**Comment by joerick** [comment]
Yep, defo agreed. I'm thinking putting the packages that electron-builder chucks out into a GitHub release is 90% of the work here. I'm thinking we can fit [Nuts](https://github.com/GitbookIO/nuts) onto a Heroku free tier. Happy to look at getting that hosted.

**Comment by joerick** [comment]
I've set up a Nuts server at http://tide-download.tingbot.com. All set up to serve downloads from releases on this repo.

**Comment by joerick** [comment]
Implemented for Mac in 5d44836fb7f5cc7957653b4219ef5c74873434bf and for Windows in c2dbfc9a2c5fa17361cbab87aa3039f4aaaba401
