### ISSUE TITLE
Properly style app

### ISSUE THREAD

**Issue by Rob4001** [tingbot/tide-electron#4]
Currently the main screen is prototype standard:

The styling should look as good as Tide before a proper release is created

**Comment by joerick** [comment]
This can serve as a reference image:

![image](https://cloud.githubusercontent.com/assets/1244307/12139964/045a3966-b45c-11e5-8a1a-ff13cf419b50.png)

Naturally concessions can be made for the current platform, notably the device menu ('Tingbot Simulator' above).

**Comment by joerick** [comment]
I'm doing a bit of work on this, pull request is coming!
