### ISSUE TITLE
WiFi Setup util shouldn't have a menubar on Windows if possible 

### ISSUE THREAD

**Issue by PhilipGilbanks** [tingbot/tide-electron#45]
![image](https://cloud.githubusercontent.com/assets/7601527/18231960/09d3e66a-72bd-11e6-982c-a565407432f7.png)

**Comment by PhilipGilbanks** [comment]
Also button not visible on windows
![image](https://cloud.githubusercontent.com/assets/7601527/18231974/70b89d08-72bd-11e6-8336-de4564282c7e.png)

**Comment by Rob4001** [comment]
Fixed by e23f81b06a6cefc210101bafd3a1696d5a0082a9
