### ISSUE TITLE
Tide on Raspberry Pi

### ISSUE THREAD

**Issue by rodrigobarnes** [tingbot/tide-electron#48]
hi 

I would like to run Tide on a second Raspberry Pi but the current packages are compiled for amd64 not ARM. Would it be possible to get a package compiled for Pi?

Thanks

**Comment by Rob4001** [comment]
Hey,

From my knowledge I don't think electron (the underlying framework we have built tide on) has a arm version.

I will have a look into it but this is unlikely to be implemented in the short term

**Comment by joerick** [comment]
I notice that there are ARM builds at https://github.com/electron/electron/releases, so this might be possible. Would be interested if somebody wants to give it a try!

**Comment by rodrigobarnes** [comment]
Thanks @joerick that's hopeful - maybe I can help with some guidance! One thing that would be important to let users know is that if they are able to run Tide on the Pi and wanted to USB power the Tingbot there would probably be power issues.

**Comment by Rob4001** [comment]
This should be implemented as of b5dab3496bae4d79f6b0b31cbeb979a34978ebb4  
Next time @joerick performs a new release it will be up on github
