### ISSUE TITLE
Tide on OS X Can't see Tingbot when connected via "Internet Sharing" WiFi

### ISSUE THREAD

**Issue by omgmog** [tingbot/tide-electron#53]
**Tide version**: 0.3.5 (0.3.5.99) OS X

Had it connected to my regular WiFi at home without any problems.

Now at my office I've got it connected to the "Internet Sharing" WiFi on my Mac, and Tide can't find the Tingbot.

![screen shot 2016-09-22 at 09 49 24](https://cloud.githubusercontent.com/assets/50949/18741988/e47bbb4a-80a9-11e6-983e-d6e45c6ceb40.png)

As you can see it's connected:

![img_20160922_095034](https://cloud.githubusercontent.com/assets/50949/18742117/7cba9516-80aa-11e6-939a-26c3a11640c1.jpg)

But Tide doesn't recognise that it's available:

![screen shot 2016-09-22 at 09 54 42](https://cloud.githubusercontent.com/assets/50949/18742153/a1457c0c-80aa-11e6-8ffe-d81ac46bcfa0.png)

**Comment by joerick** [comment]
Hey @omgmog - thanks for the report. Sometimes I've noticed that rebooting Tide can solve discovery problems like this when there's a network change, did you try that?

I also think it would be useful for advanced users like yourself to enter an IP address manually, which would be a good workaround this problem if we can't solve it in all cases.

**Comment by omgmog** [comment]
Hi @joerick yeah I tried both restarting Tide and rebooting the Tingbot, in various orders.

I'll switch to a manual IP address a bit later and see if that works. Cheers.

**Comment by joerick** [comment]
Sorry I meant that you could enter your DHCP-assigned IP address into Tide, to skip the discovery process entirely. But that feature doesn't exist yet.

**Comment by joerick** [comment]
In the meantime, here's a workaround...
- Choose **Window** > **Toggle Developer Tools** from the menu
- Find the JS console and paste into there:
  `window.vueInstance.$children[0].$children[0].devices.push({name:'192.168.2.13',target:'192.168.2.13'})
  `

**Comment by omgmog** [comment]
That works perfectly, and is a good enough solution for me in the odd case that I'm connected this way.

Cheers!

**Comment by ghost** [comment]
yeah this works for me too... thanks :)
