### ISSUE TITLE
Permissions issues on Linux install

### ISSUE THREAD

**Issue by mathieg2** [tingbot/tide-electron#54]
I am able to load the ide on ubuntu but not able to  send my code to the simulator or the tingbot

error is:

/usr/bin/python: No module named tbtool                                                               

Process exited with code 1.

**Comment by joerick** [comment]
Tide is expecting to see Python 2.7. What is `python` on your system?

**Comment by mathieg2** [comment]
i am running 2.7.12 so that should be ok. is there some sort of module in /opt/tide that the ide might not be finding?

**Comment by mathieg2** [comment]
I cleared the issue myself by running chown -R mathieg2:mathieg2 \* in /opt/Tide but i think someone needs to look at the permissions for the directories. especially /opt/Tide/resources/vendor/tide-packages which is only readable by root

**Comment by joerick** [comment]
Great, thanks for letting us know. 👍

**Comment by Rob4001** [comment]
This seems to be related specifically to the deb file format, I am installing a VM to test this more
