### ISSUE TITLE
macOS Sierra build-python issues.

### ISSUE THREAD

**Issue by fleeting** [tingbot/tide-electron#56]
Attempting to run this on the latest version of macOS (10.12) and when running `npm run build-python` it errors out with `pygame-1.9.2pre-3-cp27-cp27m-macosx_10_9_x86_64.whl is not a supported wheel on this platform.`

**Comment by joerick** [comment]
I just upgraded yesterday and it's still building okay for me! What version of `pip` and `setuptools` have you got installed? Maybe they need an update. I'm on pip 8.1.2 and setuptools 26.0.0.

**Comment by fleeting** [comment]
Hmmm, I've got pip 8.1.2, setuptools 27.3.0, node 4.5.0, and python 2.7.10. My setuptools was initially really outdated but still fails after bumping it to v27.

**Comment by joerick** [comment]
Could you run the following command and tell me the output?

```
python -c "import sys; print 'sys.path', sys.path; import setuptools; print 'setuptools version', setuptools.__version__; from pip.pep425tags import supported_tags; print 'supported_tags', supported_tags"
```

**Comment by fleeting** [comment]
Yep, here is the output - https://gist.github.com/fleeting/725961d518f8219c700aaf4adb5b5eea. I'll dig into it a little more since I know it's not macOS Sierra and something with my setup.

**Comment by joerick** [comment]
Try removing that setuptools egg that's on your path, and the entry in easy_install.pth.

**Comment by fleeting** [comment]
Success! I did the above and ended up uninstalling `setuptools` entirely. Reinstalled and got it running. Thanks for the help. Now to wait for my Tingbot to arrive in the mail. :)

**Comment by fleeting** [comment]
and it arrived today! Now to get coding.
