### ISSUE TITLE
Warn users when dependencies have not been met

### ISSUE THREAD

**Issue by Rob4001** [tingbot/tide-electron#6]
Currently it prints out on the console, it needs to at least be an alert box or similar as the console will not be shown on release versions

**Comment by joerick** [comment]
Which dependencies are these? I'm wondering if we can we bundle them...

**Comment by Rob4001** [comment]
Only dependency that you would need is tingbot-python... and it's dependencies. I have already implemented these checks to be run just before the run/upload buttons are pressed but it outputs to console not an alert box
